export class bitfield {}
export class charARB {}
export class clampf {}
export class g_boolean {}
export class g_enum {}
export class float {}
export class handleARB {}
export class int {}
export class intptr {}
export class sizei {}
export class sizeiptr {}
export class uint {}
export class g_void {}
export function InitNames(): void;
