export class Node {}
export class NodePtr {}
export class Doc {}
export class DocPtr {}
export class NsPtr {}
export class Char {}
export class TextWriter {}
export class TextReader {}
export function dummy(): void;
