export class Flags {}
export class Bool32 {}
export class DeviceSize {}
export class SampleMask {}
export class Instance {}
export class PhysicalDevice {}
export class Device {}
export class Queue {}
export class Semaphore {}
export class CommandBuffer {}
export class Fence {}
export class DeviceMemory {}
export class Buffer {}
export class Image {}
export class Event {}
export class QueryPool {}
export class BufferView {}
export class ImageView {}
export class ShaderModule {}
export class PipelineCache {}
export class PipelineLayout {}
export class RenderPass {}
export class Pipeline {}
export class DescriptorSetLayout {}
export class Sampler {}
export class DescriptorPool {}
export class DescriptorSet {}
export class Framebuffer {}
export class CommandPool {}
export class PipelineCacheHeaderVersion {}
export class Result {}
export class StructureType {}
export class SystemAllocationScope {}
export class InternalAllocationType {}
export class Format {}
export class ImageType {}
export class ImageTiling {}
export class PhysicalDeviceType {}
export class QueryType {}
export class SharingMode {}
export class ImageLayout {}
export class ImageViewType {}
export class ComponentSwizzle {}
export class VertexInputRate {}
export class PrimitiveTopology {}
export class PolygonMode {}
export class FrontFace {}
export class CompareOp {}
export class StencilOp {}
export class LogicOp {}
export class BlendFactor {}
export class BlendOp {}
export class DynamicState {}
export class Filter {}
export class SamplerMipmapMode {}
export class SamplerAddressMode {}
export class BorderColor {}
export class DescriptorType {}
export class AttachmentLoadOp {}
export class AttachmentStoreOp {}
export class PipelineBindPoint {}
export class CommandBufferLevel {}
export class IndexType {}
export class SubpassContents {}
export class ObjectType {}
export class VendorId {}
export class InstanceCreateFlags {}
export class FormatFeatureFlagBits {}
export class FormatFeatureFlags {}
export class ImageUsageFlagBits {}
export class ImageUsageFlags {}
export class ImageCreateFlagBits {}
export class ImageCreateFlags {}
export class SampleCountFlagBits {}
export class SampleCountFlags {}
export class QueueFlagBits {}
export class QueueFlags {}
export class MemoryPropertyFlagBits {}
export class MemoryPropertyFlags {}
export class MemoryHeapFlagBits {}
export class MemoryHeapFlags {}
export class DeviceCreateFlags {}
export class DeviceQueueCreateFlagBits {}
export class DeviceQueueCreateFlags {}
export class PipelineStageFlagBits {}
export class PipelineStageFlags {}
export class MemoryMapFlags {}
export class ImageAspectFlagBits {}
export class ImageAspectFlags {}
export class SparseImageFormatFlagBits {}
export class SparseImageFormatFlags {}
export class SparseMemoryBindFlagBits {}
export class SparseMemoryBindFlags {}
export class FenceCreateFlagBits {}
export class FenceCreateFlags {}
export class SemaphoreCreateFlags {}
export class EventCreateFlags {}
export class QueryPoolCreateFlags {}
export class QueryPipelineStatisticFlagBits {}
export class QueryPipelineStatisticFlags {}
export class QueryResultFlagBits {}
export class QueryResultFlags {}
export class BufferCreateFlagBits {}
export class BufferCreateFlags {}
export class BufferUsageFlagBits {}
export class BufferUsageFlags {}
export class BufferViewCreateFlags {}
export class ImageViewCreateFlagBits {}
export class ImageViewCreateFlags {}
export class ShaderModuleCreateFlags {}
export class PipelineCacheCreateFlags {}
export class PipelineCreateFlagBits {}
export class PipelineCreateFlags {}
export class PipelineShaderStageCreateFlags {}
export class ShaderStageFlagBits {}
export class PipelineVertexInputStateCreateFlags {}
export class PipelineInputAssemblyStateCreateFlags {}
export class PipelineTessellationStateCreateFlags {}
export class PipelineViewportStateCreateFlags {}
export class PipelineRasterizationStateCreateFlags {}
export class CullModeFlagBits {}
export class CullModeFlags {}
export class PipelineMultisampleStateCreateFlags {}
export class PipelineDepthStencilStateCreateFlags {}
export class PipelineColorBlendStateCreateFlags {}
export class ColorComponentFlagBits {}
export class ColorComponentFlags {}
export class PipelineDynamicStateCreateFlags {}
export class PipelineLayoutCreateFlags {}
export class ShaderStageFlags {}
export class SamplerCreateFlagBits {}
export class SamplerCreateFlags {}
export class DescriptorSetLayoutCreateFlagBits {}
export class DescriptorSetLayoutCreateFlags {}
export class DescriptorPoolCreateFlagBits {}
export class DescriptorPoolCreateFlags {}
export class DescriptorPoolResetFlags {}
export class FramebufferCreateFlags {}
export class RenderPassCreateFlags {}
export class AttachmentDescriptionFlagBits {}
export class AttachmentDescriptionFlags {}
export class SubpassDescriptionFlagBits {}
export class SubpassDescriptionFlags {}
export class AccessFlagBits {}
export class AccessFlags {}
export class DependencyFlagBits {}
export class DependencyFlags {}
export class CommandPoolCreateFlagBits {}
export class CommandPoolCreateFlags {}
export class CommandPoolResetFlagBits {}
export class CommandPoolResetFlags {}
export class CommandBufferUsageFlagBits {}
export class CommandBufferUsageFlags {}
export class QueryControlFlagBits {}
export class QueryControlFlags {}
export class CommandBufferResetFlagBits {}
export class CommandBufferResetFlags {}
export class StencilFaceFlagBits {}
export class StencilFaceFlags {}
export class ApplicationInfo {}
export class InstanceCreateInfo {}
export class AllocationCallbacks {}
export class PhysicalDeviceFeatures {}
export class FormatProperties {}
export class Extent3D {}
export class ImageFormatProperties {}
export class PhysicalDeviceLimits {}
export class PhysicalDeviceSparseProperties {}
export class PhysicalDeviceProperties {}
export class QueueFamilyProperties {}
export class MemoryType {}
export class MemoryHeap {}
export class PhysicalDeviceMemoryProperties {}
export class DeviceQueueCreateInfo {}
export class DeviceCreateInfo {}
export class ExtensionProperties {}
export class LayerProperties {}
export class SubmitInfo {}
export class MemoryAllocateInfo {}
export class MappedMemoryRange {}
export class MemoryRequirements {}
export class SparseImageFormatProperties {}
export class SparseImageMemoryRequirements {}
export class SparseMemoryBind {}
export class SparseBufferMemoryBindInfo {}
export class SparseImageOpaqueMemoryBindInfo {}
export class ImageSubresource {}
export class Offset3D {}
export class SparseImageMemoryBind {}
export class SparseImageMemoryBindInfo {}
export class BindSparseInfo {}
export class FenceCreateInfo {}
export class SemaphoreCreateInfo {}
export class EventCreateInfo {}
export class QueryPoolCreateInfo {}
export class BufferCreateInfo {}
export class BufferViewCreateInfo {}
export class ImageCreateInfo {}
export class SubresourceLayout {}
export class ComponentMapping {}
export class ImageSubresourceRange {}
export class ImageViewCreateInfo {}
export class ShaderModuleCreateInfo {}
export class PipelineCacheCreateInfo {}
export class SpecializationMapEntry {}
export class SpecializationInfo {}
export class PipelineShaderStageCreateInfo {}
export class VertexInputBindingDescription {}
export class VertexInputAttributeDescription {}
export class PipelineVertexInputStateCreateInfo {}
export class PipelineInputAssemblyStateCreateInfo {}
export class PipelineTessellationStateCreateInfo {}
export class Viewport {}
export class Offset2D {}
export class Extent2D {}
export class Rect2D {}
export class PipelineViewportStateCreateInfo {}
export class PipelineRasterizationStateCreateInfo {}
export class PipelineMultisampleStateCreateInfo {}
export class StencilOpState {}
export class PipelineDepthStencilStateCreateInfo {}
export class PipelineColorBlendAttachmentState {}
export class PipelineColorBlendStateCreateInfo {}
export class PipelineDynamicStateCreateInfo {}
export class GraphicsPipelineCreateInfo {}
export class ComputePipelineCreateInfo {}
export class PushConstantRange {}
export class PipelineLayoutCreateInfo {}
export class SamplerCreateInfo {}
export class DescriptorSetLayoutBinding {}
export class DescriptorSetLayoutCreateInfo {}
export class DescriptorPoolSize {}
export class DescriptorPoolCreateInfo {}
export class DescriptorSetAllocateInfo {}
export class DescriptorImageInfo {}
export class DescriptorBufferInfo {}
export class WriteDescriptorSet {}
export class CopyDescriptorSet {}
export class FramebufferCreateInfo {}
export class AttachmentDescription {}
export class AttachmentReference {}
export class SubpassDescription {}
export class SubpassDependency {}
export class RenderPassCreateInfo {}
export class CommandPoolCreateInfo {}
export class CommandBufferAllocateInfo {}
export class CommandBufferInheritanceInfo {}
export class CommandBufferBeginInfo {}
export class BufferCopy {}
export class ImageSubresourceLayers {}
export class ImageCopy {}
export class ImageBlit {}
export class BufferImageCopy {}
export class ClearColorValue {}
export class ClearDepthStencilValue {}
export class ClearValue {}
export class ClearAttachment {}
export class ClearRect {}
export class ImageResolve {}
export class MemoryBarrier {}
export class BufferMemoryBarrier {}
export class ImageMemoryBarrier {}
export class RenderPassBeginInfo {}
export class DispatchIndirectCommand {}
export class DrawIndexedIndirectCommand {}
export class DrawIndirectCommand {}
export class BaseOutStructure {}
export class BaseInStructure {}
export class SamplerYcbcrConversion {}
export class DescriptorUpdateTemplate {}
export class PointClippingBehavior {}
export class TessellationDomainOrigin {}
export class SamplerYcbcrModelConversion {}
export class SamplerYcbcrRange {}
export class ChromaLocation {}
export class DescriptorUpdateTemplateType {}
export class SubgroupFeatureFlagBits {}
export class SubgroupFeatureFlags {}
export class PeerMemoryFeatureFlagBits {}
export class PeerMemoryFeatureFlags {}
export class MemoryAllocateFlagBits {}
export class MemoryAllocateFlags {}
export class CommandPoolTrimFlags {}
export class DescriptorUpdateTemplateCreateFlags {}
export class ExternalMemoryHandleTypeFlagBits {}
export class ExternalMemoryHandleTypeFlags {}
export class ExternalMemoryFeatureFlagBits {}
export class ExternalMemoryFeatureFlags {}
export class ExternalFenceHandleTypeFlagBits {}
export class ExternalFenceHandleTypeFlags {}
export class ExternalFenceFeatureFlagBits {}
export class ExternalFenceFeatureFlags {}
export class FenceImportFlagBits {}
export class FenceImportFlags {}
export class SemaphoreImportFlagBits {}
export class SemaphoreImportFlags {}
export class ExternalSemaphoreHandleTypeFlagBits {}
export class ExternalSemaphoreHandleTypeFlags {}
export class ExternalSemaphoreFeatureFlagBits {}
export class ExternalSemaphoreFeatureFlags {}
export class PhysicalDeviceSubgroupProperties {}
export class BindBufferMemoryInfo {}
export class BindImageMemoryInfo {}
export class PhysicalDevice16BitStorageFeatures {}
export class MemoryDedicatedRequirements {}
export class MemoryDedicatedAllocateInfo {}
export class MemoryAllocateFlagsInfo {}
export class DeviceGroupRenderPassBeginInfo {}
export class DeviceGroupCommandBufferBeginInfo {}
export class DeviceGroupSubmitInfo {}
export class DeviceGroupBindSparseInfo {}
export class BindBufferMemoryDeviceGroupInfo {}
export class BindImageMemoryDeviceGroupInfo {}
export class PhysicalDeviceGroupProperties {}
export class DeviceGroupDeviceCreateInfo {}
export class BufferMemoryRequirementsInfo2 {}
export class ImageMemoryRequirementsInfo2 {}
export class ImageSparseMemoryRequirementsInfo2 {}
export class MemoryRequirements2 {}
export class MemoryRequirements2KHR {}
export class SparseImageMemoryRequirements2 {}
export class PhysicalDeviceFeatures2 {}
export class PhysicalDeviceProperties2 {}
export class FormatProperties2 {}
export class ImageFormatProperties2 {}
export class PhysicalDeviceImageFormatInfo2 {}
export class QueueFamilyProperties2 {}
export class PhysicalDeviceMemoryProperties2 {}
export class SparseImageFormatProperties2 {}
export class PhysicalDeviceSparseImageFormatInfo2 {}
export class PhysicalDevicePointClippingProperties {}
export class InputAttachmentAspectReference {}
export class RenderPassInputAttachmentAspectCreateInfo {}
export class ImageViewUsageCreateInfo {}
export class PipelineTessellationDomainOriginStateCreateInfo {}
export class RenderPassMultiviewCreateInfo {}
export class PhysicalDeviceMultiviewFeatures {}
export class PhysicalDeviceMultiviewProperties {}
export class PhysicalDeviceVariablePointersFeatures {}
export class PhysicalDeviceVariablePointerFeatures {}
export class PhysicalDeviceProtectedMemoryFeatures {}
export class PhysicalDeviceProtectedMemoryProperties {}
export class DeviceQueueInfo2 {}
export class ProtectedSubmitInfo {}
export class SamplerYcbcrConversionCreateInfo {}
export class SamplerYcbcrConversionInfo {}
export class BindImagePlaneMemoryInfo {}
export class ImagePlaneMemoryRequirementsInfo {}
export class PhysicalDeviceSamplerYcbcrConversionFeatures {}
export class SamplerYcbcrConversionImageFormatProperties {}
export class DescriptorUpdateTemplateEntry {}
export class DescriptorUpdateTemplateCreateInfo {}
export class ExternalMemoryProperties {}
export class PhysicalDeviceExternalImageFormatInfo {}
export class ExternalImageFormatProperties {}
export class PhysicalDeviceExternalBufferInfo {}
export class ExternalBufferProperties {}
export class PhysicalDeviceIDProperties {}
export class ExternalMemoryImageCreateInfo {}
export class ExternalMemoryBufferCreateInfo {}
export class ExportMemoryAllocateInfo {}
export class PhysicalDeviceExternalFenceInfo {}
export class ExternalFenceProperties {}
export class ExportFenceCreateInfo {}
export class ExportSemaphoreCreateInfo {}
export class PhysicalDeviceExternalSemaphoreInfo {}
export class ExternalSemaphoreProperties {}
export class PhysicalDeviceMaintenance3Properties {}
export class DescriptorSetLayoutSupport {}
export class PhysicalDeviceShaderDrawParametersFeatures {}
export class PhysicalDeviceShaderDrawParameterFeatures {}
export class SurfaceKHR {}
export class ColorSpaceKHR {}
export class PresentModeKHR {}
export class SurfaceTransformFlagBitsKHR {}
export class SurfaceTransformFlagsKHR {}
export class CompositeAlphaFlagBitsKHR {}
export class CompositeAlphaFlagsKHR {}
export class SurfaceCapabilitiesKHR {}
export class SurfaceFormatKHR {}
export class SwapchainKHR {}
export class SwapchainCreateFlagBitsKHR {}
export class SwapchainCreateFlagsKHR {}
export class DeviceGroupPresentModeFlagBitsKHR {}
export class DeviceGroupPresentModeFlagsKHR {}
export class SwapchainCreateInfoKHR {}
export class PresentInfoKHR {}
export class ImageSwapchainCreateInfoKHR {}
export class BindImageMemorySwapchainInfoKHR {}
export class AcquireNextImageInfoKHR {}
export class DeviceGroupPresentCapabilitiesKHR {}
export class DeviceGroupPresentInfoKHR {}
export class DeviceGroupSwapchainCreateInfoKHR {}
export class DisplayKHR {}
export class DisplayModeKHR {}
export class DisplayPlaneAlphaFlagBitsKHR {}
export class DisplayPlaneAlphaFlagsKHR {}
export class DisplayModeCreateFlagsKHR {}
export class DisplaySurfaceCreateFlagsKHR {}
export class DisplayPropertiesKHR {}
export class DisplayModeParametersKHR {}
export class DisplayModePropertiesKHR {}
export class DisplayModeCreateInfoKHR {}
export class DisplayPlaneCapabilitiesKHR {}
export class DisplayPlanePropertiesKHR {}
export class DisplaySurfaceCreateInfoKHR {}
export class DisplayPresentInfoKHR {}
export class RenderPassMultiviewCreateInfoKHR {}
export class PhysicalDeviceMultiviewFeaturesKHR {}
export class PhysicalDeviceMultiviewPropertiesKHR {}
export class PhysicalDeviceFeatures2KHR {}
export class PhysicalDeviceProperties2KHR {}
export class FormatProperties2KHR {}
export class ImageFormatProperties2KHR {}
export class PhysicalDeviceImageFormatInfo2KHR {}
export class QueueFamilyProperties2KHR {}
export class PhysicalDeviceMemoryProperties2KHR {}
export class SparseImageFormatProperties2KHR {}
export class PhysicalDeviceSparseImageFormatInfo2KHR {}
export class PeerMemoryFeatureFlagsKHR {}
export class PeerMemoryFeatureFlagBitsKHR {}
export class MemoryAllocateFlagsKHR {}
export class MemoryAllocateFlagBitsKHR {}
export class MemoryAllocateFlagsInfoKHR {}
export class DeviceGroupRenderPassBeginInfoKHR {}
export class DeviceGroupCommandBufferBeginInfoKHR {}
export class DeviceGroupSubmitInfoKHR {}
export class DeviceGroupBindSparseInfoKHR {}
export class BindBufferMemoryDeviceGroupInfoKHR {}
export class BindImageMemoryDeviceGroupInfoKHR {}
export class CommandPoolTrimFlagsKHR {}
export class PhysicalDeviceGroupPropertiesKHR {}
export class DeviceGroupDeviceCreateInfoKHR {}
export class ExternalMemoryHandleTypeFlagsKHR {}
export class ExternalMemoryHandleTypeFlagBitsKHR {}
export class ExternalMemoryFeatureFlagsKHR {}
export class ExternalMemoryFeatureFlagBitsKHR {}
export class ExternalMemoryPropertiesKHR {}
export class PhysicalDeviceExternalImageFormatInfoKHR {}
export class ExternalImageFormatPropertiesKHR {}
export class PhysicalDeviceExternalBufferInfoKHR {}
export class ExternalBufferPropertiesKHR {}
export class PhysicalDeviceIDPropertiesKHR {}
export class ExternalMemoryImageCreateInfoKHR {}
export class ExternalMemoryBufferCreateInfoKHR {}
export class ExportMemoryAllocateInfoKHR {}
export class ImportMemoryFdInfoKHR {}
export class MemoryFdPropertiesKHR {}
export class MemoryGetFdInfoKHR {}
export class ExternalSemaphoreHandleTypeFlagsKHR {}
export class ExternalSemaphoreHandleTypeFlagBitsKHR {}
export class ExternalSemaphoreFeatureFlagsKHR {}
export class ExternalSemaphoreFeatureFlagBitsKHR {}
export class PhysicalDeviceExternalSemaphoreInfoKHR {}
export class ExternalSemaphorePropertiesKHR {}
export class SemaphoreImportFlagsKHR {}
export class SemaphoreImportFlagBitsKHR {}
export class ExportSemaphoreCreateInfoKHR {}
export class ImportSemaphoreFdInfoKHR {}
export class SemaphoreGetFdInfoKHR {}
export class PhysicalDevicePushDescriptorPropertiesKHR {}
export class PhysicalDeviceFloat16Int8FeaturesKHR {}
export class PhysicalDevice16BitStorageFeaturesKHR {}
export class RectLayerKHR {}
export class PresentRegionKHR {}
export class PresentRegionsKHR {}
export class DescriptorUpdateTemplateKHR {}
export class DescriptorUpdateTemplateTypeKHR {}
export class DescriptorUpdateTemplateCreateFlagsKHR {}
export class DescriptorUpdateTemplateEntryKHR {}
export class DescriptorUpdateTemplateCreateInfoKHR {}
export class AttachmentDescription2KHR {}
export class AttachmentReference2KHR {}
export class SubpassDescription2KHR {}
export class SubpassDependency2KHR {}
export class RenderPassCreateInfo2KHR {}
export class SubpassBeginInfoKHR {}
export class SubpassEndInfoKHR {}
export class SharedPresentSurfaceCapabilitiesKHR {}
export class ExternalFenceHandleTypeFlagsKHR {}
export class ExternalFenceHandleTypeFlagBitsKHR {}
export class ExternalFenceFeatureFlagsKHR {}
export class ExternalFenceFeatureFlagBitsKHR {}
export class PhysicalDeviceExternalFenceInfoKHR {}
export class ExternalFencePropertiesKHR {}
export class FenceImportFlagsKHR {}
export class FenceImportFlagBitsKHR {}
export class ExportFenceCreateInfoKHR {}
export class ImportFenceFdInfoKHR {}
export class FenceGetFdInfoKHR {}
export class PointClippingBehaviorKHR {}
export class TessellationDomainOriginKHR {}
export class PhysicalDevicePointClippingPropertiesKHR {}
export class RenderPassInputAttachmentAspectCreateInfoKHR {}
export class InputAttachmentAspectReferenceKHR {}
export class ImageViewUsageCreateInfoKHR {}
export class PipelineTessellationDomainOriginStateCreateInfoKHR {}
export class PhysicalDeviceSurfaceInfo2KHR {}
export class SurfaceCapabilities2KHR {}
export class SurfaceFormat2KHR {}
export class PhysicalDeviceVariablePointerFeaturesKHR {}
export class PhysicalDeviceVariablePointersFeaturesKHR {}
export class DisplayProperties2KHR {}
export class DisplayPlaneProperties2KHR {}
export class DisplayModeProperties2KHR {}
export class DisplayPlaneInfo2KHR {}
export class DisplayPlaneCapabilities2KHR {}
export class MemoryDedicatedRequirementsKHR {}
export class MemoryDedicatedAllocateInfoKHR {}
export class BufferMemoryRequirementsInfo2KHR {}
export class ImageMemoryRequirementsInfo2KHR {}
export class ImageSparseMemoryRequirementsInfo2KHR {}
export class SparseImageMemoryRequirements2KHR {}
export class ImageFormatListCreateInfoKHR {}
export class SamplerYcbcrConversionKHR {}
export class SamplerYcbcrModelConversionKHR {}
export class SamplerYcbcrRangeKHR {}
export class ChromaLocationKHR {}
export class SamplerYcbcrConversionCreateInfoKHR {}
export class SamplerYcbcrConversionInfoKHR {}
export class BindImagePlaneMemoryInfoKHR {}
export class ImagePlaneMemoryRequirementsInfoKHR {}
export class PhysicalDeviceSamplerYcbcrConversionFeaturesKHR {}
export class SamplerYcbcrConversionImageFormatPropertiesKHR {}
export class BindBufferMemoryInfoKHR {}
export class BindImageMemoryInfoKHR {}
export class PhysicalDeviceMaintenance3PropertiesKHR {}
export class DescriptorSetLayoutSupportKHR {}
export class PhysicalDevice8BitStorageFeaturesKHR {}
export class PhysicalDeviceShaderAtomicInt64FeaturesKHR {}
export class DriverIdKHR {}
export class ConformanceVersionKHR {}
export class PhysicalDeviceDriverPropertiesKHR {}
export class PhysicalDeviceFloatControlsPropertiesKHR {}
export class ResolveModeFlagBitsKHR {}
export class ResolveModeFlagsKHR {}
export class SubpassDescriptionDepthStencilResolveKHR {}
export class PhysicalDeviceDepthStencilResolvePropertiesKHR {}
export class PhysicalDeviceVulkanMemoryModelFeaturesKHR {}
export class SurfaceProtectedCapabilitiesKHR {}
export class PhysicalDeviceUniformBufferStandardLayoutFeaturesKHR {}
export class DebugReportCallbackEXT {}
export class DebugReportObjectTypeEXT {}
export class DebugReportFlagBitsEXT {}
export class DebugReportFlagsEXT {}
export class DebugReportCallbackCreateInfoEXT {}
export class RasterizationOrderAMD {}
export class PipelineRasterizationStateRasterizationOrderAMD {}
export class DebugMarkerObjectNameInfoEXT {}
export class DebugMarkerObjectTagInfoEXT {}
export class DebugMarkerMarkerInfoEXT {}
export class DedicatedAllocationImageCreateInfoNV {}
export class DedicatedAllocationBufferCreateInfoNV {}
export class DedicatedAllocationMemoryAllocateInfoNV {}
export class PipelineRasterizationStateStreamCreateFlagsEXT {}
export class PhysicalDeviceTransformFeedbackFeaturesEXT {}
export class PhysicalDeviceTransformFeedbackPropertiesEXT {}
export class PipelineRasterizationStateStreamCreateInfoEXT {}
export class ImageViewHandleInfoNVX {}
export class TextureLODGatherFormatPropertiesAMD {}
export class ShaderInfoTypeAMD {}
export class ShaderResourceUsageAMD {}
export class ShaderStatisticsInfoAMD {}
export class PhysicalDeviceCornerSampledImageFeaturesNV {}
export class ExternalMemoryHandleTypeFlagBitsNV {}
export class ExternalMemoryHandleTypeFlagsNV {}
export class ExternalMemoryFeatureFlagBitsNV {}
export class ExternalMemoryFeatureFlagsNV {}
export class ExternalImageFormatPropertiesNV {}
export class ExternalMemoryImageCreateInfoNV {}
export class ExportMemoryAllocateInfoNV {}
export class ValidationCheckEXT {}
export class ValidationFlagsEXT {}
export class ImageViewASTCDecodeModeEXT {}
export class PhysicalDeviceASTCDecodeFeaturesEXT {}
export class ConditionalRenderingFlagBitsEXT {}
export class ConditionalRenderingFlagsEXT {}
export class ConditionalRenderingBeginInfoEXT {}
export class PhysicalDeviceConditionalRenderingFeaturesEXT {}
export class CommandBufferInheritanceConditionalRenderingInfoEXT {}
export class ObjectTableNVX {}
export class IndirectCommandsLayoutNVX {}
export class IndirectCommandsTokenTypeNVX {}
export class ObjectEntryTypeNVX {}
export class IndirectCommandsLayoutUsageFlagBitsNVX {}
export class IndirectCommandsLayoutUsageFlagsNVX {}
export class ObjectEntryUsageFlagBitsNVX {}
export class ObjectEntryUsageFlagsNVX {}
export class DeviceGeneratedCommandsFeaturesNVX {}
export class DeviceGeneratedCommandsLimitsNVX {}
export class IndirectCommandsTokenNVX {}
export class IndirectCommandsLayoutTokenNVX {}
export class IndirectCommandsLayoutCreateInfoNVX {}
export class CmdProcessCommandsInfoNVX {}
export class CmdReserveSpaceForCommandsInfoNVX {}
export class ObjectTableCreateInfoNVX {}
export class ObjectTableEntryNVX {}
export class ObjectTablePipelineEntryNVX {}
export class ObjectTableDescriptorSetEntryNVX {}
export class ObjectTableVertexBufferEntryNVX {}
export class ObjectTableIndexBufferEntryNVX {}
export class ObjectTablePushConstantEntryNVX {}
export class ViewportWScalingNV {}
export class PipelineViewportWScalingStateCreateInfoNV {}
export class SurfaceCounterFlagBitsEXT {}
export class SurfaceCounterFlagsEXT {}
export class SurfaceCapabilities2EXT {}
export class DisplayPowerStateEXT {}
export class DeviceEventTypeEXT {}
export class DisplayEventTypeEXT {}
export class DisplayPowerInfoEXT {}
export class DeviceEventInfoEXT {}
export class DisplayEventInfoEXT {}
export class SwapchainCounterCreateInfoEXT {}
export class RefreshCycleDurationGOOGLE {}
export class PastPresentationTimingGOOGLE {}
export class PresentTimeGOOGLE {}
export class PresentTimesInfoGOOGLE {}
export class PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX {}
export class ViewportCoordinateSwizzleNV {}
export class PipelineViewportSwizzleStateCreateFlagsNV {}
export class ViewportSwizzleNV {}
export class PipelineViewportSwizzleStateCreateInfoNV {}
export class DiscardRectangleModeEXT {}
export class PipelineDiscardRectangleStateCreateFlagsEXT {}
export class PhysicalDeviceDiscardRectanglePropertiesEXT {}
export class PipelineDiscardRectangleStateCreateInfoEXT {}
export class ConservativeRasterizationModeEXT {}
export class PipelineRasterizationConservativeStateCreateFlagsEXT {}
export class PhysicalDeviceConservativeRasterizationPropertiesEXT {}
export class PipelineRasterizationConservativeStateCreateInfoEXT {}
export class PipelineRasterizationDepthClipStateCreateFlagsEXT {}
export class PhysicalDeviceDepthClipEnableFeaturesEXT {}
export class PipelineRasterizationDepthClipStateCreateInfoEXT {}
export class XYColorEXT {}
export class HdrMetadataEXT {}
export class DebugUtilsMessengerEXT {}
export class DebugUtilsMessengerCallbackDataFlagsEXT {}
export class DebugUtilsMessengerCreateFlagsEXT {}
export class DebugUtilsMessageSeverityFlagBitsEXT {}
export class DebugUtilsMessageSeverityFlagsEXT {}
export class DebugUtilsMessageTypeFlagBitsEXT {}
export class DebugUtilsMessageTypeFlagsEXT {}
export class DebugUtilsObjectNameInfoEXT {}
export class DebugUtilsObjectTagInfoEXT {}
export class DebugUtilsLabelEXT {}
export class DebugUtilsMessengerCallbackDataEXT {}
export class DebugUtilsMessengerCreateInfoEXT {}
export class SamplerReductionModeEXT {}
export class SamplerReductionModeCreateInfoEXT {}
export class PhysicalDeviceSamplerFilterMinmaxPropertiesEXT {}
export class PhysicalDeviceInlineUniformBlockFeaturesEXT {}
export class PhysicalDeviceInlineUniformBlockPropertiesEXT {}
export class WriteDescriptorSetInlineUniformBlockEXT {}
export class DescriptorPoolInlineUniformBlockCreateInfoEXT {}
export class SampleLocationEXT {}
export class SampleLocationsInfoEXT {}
export class AttachmentSampleLocationsEXT {}
export class SubpassSampleLocationsEXT {}
export class RenderPassSampleLocationsBeginInfoEXT {}
export class PipelineSampleLocationsStateCreateInfoEXT {}
export class PhysicalDeviceSampleLocationsPropertiesEXT {}
export class MultisamplePropertiesEXT {}
export class BlendOverlapEXT {}
export class PhysicalDeviceBlendOperationAdvancedFeaturesEXT {}
export class PhysicalDeviceBlendOperationAdvancedPropertiesEXT {}
export class PipelineColorBlendAdvancedStateCreateInfoEXT {}
export class PipelineCoverageToColorStateCreateFlagsNV {}
export class PipelineCoverageToColorStateCreateInfoNV {}
export class CoverageModulationModeNV {}
export class PipelineCoverageModulationStateCreateFlagsNV {}
export class PipelineCoverageModulationStateCreateInfoNV {}
export class DrmFormatModifierPropertiesEXT {}
export class DrmFormatModifierPropertiesListEXT {}
export class PhysicalDeviceImageDrmFormatModifierInfoEXT {}
export class ImageDrmFormatModifierListCreateInfoEXT {}
export class ImageDrmFormatModifierExplicitCreateInfoEXT {}
export class ImageDrmFormatModifierPropertiesEXT {}
export class ValidationCacheEXT {}
export class ValidationCacheHeaderVersionEXT {}
export class ValidationCacheCreateFlagsEXT {}
export class ValidationCacheCreateInfoEXT {}
export class ShaderModuleValidationCacheCreateInfoEXT {}
export class DescriptorBindingFlagBitsEXT {}
export class DescriptorBindingFlagsEXT {}
export class DescriptorSetLayoutBindingFlagsCreateInfoEXT {}
export class PhysicalDeviceDescriptorIndexingFeaturesEXT {}
export class PhysicalDeviceDescriptorIndexingPropertiesEXT {}
export class DescriptorSetVariableDescriptorCountAllocateInfoEXT {}
export class DescriptorSetVariableDescriptorCountLayoutSupportEXT {}
export class ShadingRatePaletteEntryNV {}
export class CoarseSampleOrderTypeNV {}
export class ShadingRatePaletteNV {}
export class PipelineViewportShadingRateImageStateCreateInfoNV {}
export class PhysicalDeviceShadingRateImageFeaturesNV {}
export class PhysicalDeviceShadingRateImagePropertiesNV {}
export class CoarseSampleLocationNV {}
export class CoarseSampleOrderCustomNV {}
export class PipelineViewportCoarseSampleOrderStateCreateInfoNV {}
export class AccelerationStructureNV {}
export class RayTracingShaderGroupTypeNV {}
export class GeometryTypeNV {}
export class AccelerationStructureTypeNV {}
export class CopyAccelerationStructureModeNV {}
export class AccelerationStructureMemoryRequirementsTypeNV {}
export class GeometryFlagBitsNV {}
export class GeometryFlagsNV {}
export class GeometryInstanceFlagBitsNV {}
export class GeometryInstanceFlagsNV {}
export class BuildAccelerationStructureFlagBitsNV {}
export class BuildAccelerationStructureFlagsNV {}
export class RayTracingShaderGroupCreateInfoNV {}
export class RayTracingPipelineCreateInfoNV {}
export class GeometryTrianglesNV {}
export class GeometryAABBNV {}
export class GeometryDataNV {}
export class GeometryNV {}
export class AccelerationStructureInfoNV {}
export class AccelerationStructureCreateInfoNV {}
export class BindAccelerationStructureMemoryInfoNV {}
export class WriteDescriptorSetAccelerationStructureNV {}
export class AccelerationStructureMemoryRequirementsInfoNV {}
export class PhysicalDeviceRayTracingPropertiesNV {}
export class PhysicalDeviceRepresentativeFragmentTestFeaturesNV {}
export class PipelineRepresentativeFragmentTestStateCreateInfoNV {}
export class PhysicalDeviceImageViewImageFormatInfoEXT {}
export class FilterCubicImageViewImageFormatPropertiesEXT {}
export class QueueGlobalPriorityEXT {}
export class DeviceQueueGlobalPriorityCreateInfoEXT {}
export class ImportMemoryHostPointerInfoEXT {}
export class MemoryHostPointerPropertiesEXT {}
export class PhysicalDeviceExternalMemoryHostPropertiesEXT {}
export class TimeDomainEXT {}
export class CalibratedTimestampInfoEXT {}
export class PhysicalDeviceShaderCorePropertiesAMD {}
export class MemoryOverallocationBehaviorAMD {}
export class DeviceMemoryOverallocationCreateInfoAMD {}
export class PhysicalDeviceVertexAttributeDivisorPropertiesEXT {}
export class VertexInputBindingDivisorDescriptionEXT {}
export class PipelineVertexInputDivisorStateCreateInfoEXT {}
export class PhysicalDeviceVertexAttributeDivisorFeaturesEXT {}
export class PipelineCreationFeedbackFlagBitsEXT {}
export class PipelineCreationFeedbackFlagsEXT {}
export class PipelineCreationFeedbackEXT {}
export class PipelineCreationFeedbackCreateInfoEXT {}
export class PhysicalDeviceComputeShaderDerivativesFeaturesNV {}
export class PhysicalDeviceMeshShaderFeaturesNV {}
export class PhysicalDeviceMeshShaderPropertiesNV {}
export class DrawMeshTasksIndirectCommandNV {}
export class PhysicalDeviceFragmentShaderBarycentricFeaturesNV {}
export class PhysicalDeviceShaderImageFootprintFeaturesNV {}
export class PipelineViewportExclusiveScissorStateCreateInfoNV {}
export class PhysicalDeviceExclusiveScissorFeaturesNV {}
export class QueueFamilyCheckpointPropertiesNV {}
export class CheckpointDataNV {}
export class PhysicalDevicePCIBusInfoPropertiesEXT {}
export class DisplayNativeHdrSurfaceCapabilitiesAMD {}
export class SwapchainDisplayNativeHdrCreateInfoAMD {}
export class PhysicalDeviceFragmentDensityMapFeaturesEXT {}
export class PhysicalDeviceFragmentDensityMapPropertiesEXT {}
export class RenderPassFragmentDensityMapCreateInfoEXT {}
export class PhysicalDeviceScalarBlockLayoutFeaturesEXT {}
export class PhysicalDeviceMemoryBudgetPropertiesEXT {}
export class PhysicalDeviceMemoryPriorityFeaturesEXT {}
export class MemoryPriorityAllocateInfoEXT {}
export class PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV {}
export class DeviceAddress {}
export class PhysicalDeviceBufferDeviceAddressFeaturesEXT {}
export class PhysicalDeviceBufferAddressFeaturesEXT {}
export class BufferDeviceAddressInfoEXT {}
export class BufferDeviceAddressCreateInfoEXT {}
export class ImageStencilUsageCreateInfoEXT {}
export class ValidationFeatureEnableEXT {}
export class ValidationFeatureDisableEXT {}
export class ValidationFeaturesEXT {}
export class ComponentTypeNV {}
export class ScopeNV {}
export class CooperativeMatrixPropertiesNV {}
export class PhysicalDeviceCooperativeMatrixFeaturesNV {}
export class PhysicalDeviceCooperativeMatrixPropertiesNV {}
export class CoverageReductionModeNV {}
export class PipelineCoverageReductionStateCreateFlagsNV {}
export class PhysicalDeviceCoverageReductionModeFeaturesNV {}
export class PipelineCoverageReductionStateCreateInfoNV {}
export class FramebufferMixedSamplesCombinationNV {}
export class PhysicalDeviceYcbcrImageArraysFeaturesEXT {}
export class HeadlessSurfaceCreateFlagsEXT {}
export class HeadlessSurfaceCreateInfoEXT {}
export class PhysicalDeviceHostQueryResetFeaturesEXT {}